[[plugins]]
    repo="NLKNguyen/papercolor-theme"

[[plugins]]
    repo='raphamorim/lucario'

[[plugins]]
    repo ='altercation/vim-colors-solarized'
    repo='lifepillar/vim-solarized8'

[[plugins]]
    repo='rhysd/vim-color-spring-night'

[[plugins]]
    repo='tjammer/blayu.vim'


[[plugins]]
    repo="jacoborus/tender"

[[plugins]]
    repo='connorholyday/vim-snazzy'

[[plugins]]
    repo='franbach/miramare'

[[plugins]]
    repo="jdsimcoe/panic.vim"
[[plugins]]
    repo="nanotech/jellybeans.vim"
[[plugins]]
    repo="sickill/vim-monokai"

[[pluins]]
    repo="cliuj/vim-dark-meadow"

[[plugins]]
    repo='dikiaap/minimalist'
