[[plugins]]
    repo='Yggdroot/indentLine'
    on_ft='python'
    hook_add='''
         let g:indentLine_setColors=0
        nnoremap <silent><C-i> :IndentLinesToggle<CR>
    '''

[[plugins]]
    repo='heavenshell/vim-pydocstring'
    on_ft='python'
    hook_source='''
        let g:pydocstring_enable_comment = 0
    '''

[[plugins]]
    repo = 'tweekmonster/braceless.vim'
    on_ft = 'python'
    hook_add='''
        autocmd FileType python BracelessEnable +fold
    '''
