#File
[[plugins]]
    repo='scrooloose/nerdtree'
    hook_add='''
        nnoremap <silent><C-e> :NERDTreeToggle<CR>
    '''

#ctags
[[plugins]]
    repo='majutsushi/tagbar'
    hook_add='''
        nnoremap <silent><C-t> :TagbarToggle<CR>
    '''

[[plugins]]
    repo='lilydjwg/colorizer'
    hook_add='''
        g:colorizer_maxlines=1000
    '''
