#File
[[plugins]]
    repo='scrooloose/nerdtree'
    hook_add='''
        nnoremap <silent><C-e> :NERDTreeToggle<CR>
    '''

# git
[[plugins]]
    repo="tpope/vim-fugitive"
[[plugins]]
    repo="airblade/vim-gitgutter"

#ctags
[[plugins]]
    repo='majutsushi/tagbar'
    hook_add='''
        nnoremap <silent><C-t> :TagbarToggle<CR>
    '''


