[[plugins]]
repo = 'vim-airline/vim-airline'
depends =['vim-airline-themes']
hook_add = '''
   " let g:airline_theme = 'solarized'
		let g:airline_theme = 'spring_night'
		let g:airline_solarized_bg='dark'
		let g:airline_extensions_tabline_enable=1
'''

[[plugins]]
  repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo='edkolev/tmuxline.vim'
hook_source='''
    let g:tmuxline_preset = {
    \'a'    : '#S',
    \'c'    : ['#(whoami)', '#(uptime | cud -d " " -f 1,2,3)'],
    \'win'  : ['#I', '#W'],
    \'cwin' : ['#I', '#W', '#F'],
    \'x'    : '#(date)',
    \'y'    : ['%R', '%a', '%Y'],
    \'z'    : '#H'}
    let g:tmuxline_theme = 'papercolor'
    let g:tmuxline_powerline_separators = 0
'''

[[plugins]]
		repo='scrooloose/nerdtree'
		
[[plugins]]
		repo = 'Shougo/denite.nvim'


[[plugins]] # toml syntax
		repo = 'cespare/vim-toml'
		on_ft = 'toml'

#templete
[[plugins]]
    repo='thinca/vim-template'
    hook_add='''
        let g:template_basedir='~/dotfiles'
        let g:template_free_pattern='template'
'''

#git
[[plugins]]
    repo="tpope/vim-fugitive"


