#File
[[plugins]]
    repo='scrooloose/nerdtree'
    hook_add='''
        nnoremap <silent><C-e> :NERDTreeToggle<CR>
    '''

#Syntax
[[plugins]] # toml syntax 
    repo = 'cespare/vim-toml'
    on_ft = 'toml'

# git
[[plugins]]
    repo="tpope/vim-fugitive"
[[plugins]]
    repo="airblade/vim-gitgutter"

#ctags
[[plugins]]
    repo='majutsushi/tagbar'
    hook_add='''
        nnoremap <silent><C-t> :TagbarToggle<CR>
    '''


# vim-sneak
#[[plugins]]
#    repo='justinmk/vim-sneak'
#    hook_add='''
#        let g:sneak#label = 1
#        map f <Plug>Sneak
#        map F <Plug>Sneak_S
#    '''
