[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft='python'
hook_add='''
		let g:jedi#popup_select_first = 0
   	let g:jedi#popup_on_dot= 0
'''

[[plugins]]
repo='tell-k/vim-autopep8'
on_ft='python'
hook_add='''
 " automatically fixed code on savind
	let g:autopep8_on_save=1	
 " when fixed code,do not show diff_window
  let g:autopep8_disable_show_diff=1
	let g:autopep8_indent_size=4
'''


[[plugins]]
repo='kevinw/pyflakes-vim'
on_ft='python'
hook_add='''
    let g:pyflakes_use_quickfix=0
    let g:pyflakes_prefer_python_version=3
'''
[[plugins]]
repo='Yggdroot/indentLine'
on_ft='python'
hook_source='''
    let g:indentLine_setColors=0
'''

[[plugins]]
repo='heavenshell/vim-pydocstring'
on_ft='python'
hook_source='''
    let g:pydocstring_templates_dir ='~/dotfiles/template/pydoc_template/'
    let g:pydocstring_enable_comment = 0
'''
