[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft='python'
hook_add='''
		let g:jedi#popup_select_first = 0
		let g:jedi#popup_on_dot= 0
'''

[[plugins]]
repo='tell-k/vim-autopep8'
on_ft='python'
hook_add='''
 " automatically fixed code on savind
	let g:autopep8_on_save=1	
 " when fixed code,do not show diff_window
  let g:autopep8_disable_show_diff=1
	let g:autopep8_indent_size=4
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft='python'
hook_add='''
    let g:quickrun_config = {
    \ '_' : {
        \ 'runner' : 'vimproc',
        \ 'runner/vimproc/updatetime' : 40,
        \ 'outputter' : 'error',
        \ 'outputter/error/success' : 'buffer',
        \ 'outputter/error/error'   : 'quickfix',
        \ 'outputter/buffer/split' : ':botright 8sp',
    \ }
    \}

    " 実行時に前回の表示内容をクローズ&保存してから実行
    let g:quickrun_no_default_key_mappings = 1
    '''

[[plugins]]
repo='Shougo/vimproc.vim'
on_ft='python'

[[plugins]]
repo='kevinw/pyflakes-vim'
on_ft='python'
hook_add='''
    let g:pyflakes_use_quickfix=0
    let g:pyflakes_prefer_python_version=3
'''
